# Assignment 6 Data Scaling

In [49]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
import numpy as np
import pandas as pd

In [50]:
data = pd.DataFrame(data=[[5,5],[10,2],[15,3],[20,4],[25,5]], columns=['A','B'])
data

A  B
0   5  5
1  10  2
2  15  3
3  20  4
4  25  5

### Min Max Scaler

In [51]:
scalar = MinMaxScaler()
minmax_data = scalar.fit_transform(data)
minmax_data

array([[0.        , 1.        ],
       [0.25      , 0.        ],
       [0.5       , 0.33333333],
       [0.75      , 0.66666667],
       [1.        , 1.        ]])

## Applying Scaling on DATASET

In [54]:
df = pd.read_csv("/workspaces/MonoRepo/DPEL/FILES/cryptocurrency.csv")
df

timestamp         name symbol   price_usd  vol_24h total_vol  \
0      2025-09-23 01:05:12          BNB    BNB       990.2   $4.87B     2.12%   
1      2025-09-23 01:05:12     Dogecoin   DOGE    0.241003   $5.60B     2.48%   
2      2025-09-23 01:05:12     Ethereum    ETH    4,191.67  $58.33B    24.46%   
3      2025-09-23 01:05:12      Bitcoin    BTC  112,796.60  $70.20B    28.66%   
4      2025-09-23 01:05:12          XRP    XRP      2.8519  $10.05B     4.22%   
...                    ...          ...    ...         ...      ...       ...   
94441  2025-03-17 00:34:14       Solana    SOL     127.675   $2.36B     3.90%   
94442  2025-03-17 00:34:14      Bitcoin    BTC   82,953.80  $19.36B    31.82%   
94443  2025-03-17 00:34:14          XRP    XRP      2.3201   $3.85B     6.82%   
94444  2025-03-17 00:34:14  Tether USDt   USDT           1  $46.75B    79.72%   
94445  2025-03-17 00:34:14         USDC   USDC           1   $5.16B     8.43%   

      chg_24h   chg_7d market_cap  
0      -5.70%   +7.38%   $137.66B  
1      -8.69%  -10.26%    $36.21B  
2      -6.29%   -7.10%   $506.47B  
3      -2.13%   -2.16%     $2.25T  
4      -4.49%   -5.22%   $170.09B  
...       ...      ...        ...  
94441  -6.14%   -0.46%    $64.91B  
94442  -1.66%   +0.45%     $1.64T  
94443  -4.14%   +6.16%   $134.52B  
94444  -0.01%   +0.00%   $143.45B  
94445  +0.01%   +0.00%    $58.72B  

[94446 rows x 9 columns]

#### Preprocessing the price_usd to float

In [55]:
def remove_comma(val: pd.Series) -> float:
    if '$' in val:
        val = val.replace('$','')
    if "B" in val:
        val = val.replace('B','')
        val = float(val) * 10**9
        return val
    if "M" in val:
        val = val.replace('M','')
        val = float(val) * 10**6
        return val
    if ',' in val:
        val = val.replace(',','')
        val = float(val)
        return val
    if '%' in val:
        val = np.nan
        return val
    else:
        val = float(val)
        return val

In [56]:
df["updated_usd"] = df["price_usd"].apply(remove_comma)

In [46]:
new_df = df.updated_usd.dropna().to_frame()

### MinMax Scaling

In [ ]:
scalar = MinMaxScaler()
minmaxScaled = scalar.fit_transform(new_df)
minmaxScaled

array([[1.00824762e-08],
       [2.45385317e-12],
       [4.26806841e-08],
       ...,
       [2.36237646e-11],
       [1.01821599e-11],
       [1.01821599e-11]], shape=(94430, 1))

In [ ]:
## Standard Scalar

In [57]:
scalar = StandardScaler()
standard_data = scalar.fit_transform(new_df)
standard_data

array([[-0.00587655],
       [-0.00587915],
       [-0.00586812],
       ...,
       [-0.00587915],
       [-0.00587915],
       [-0.00587915]], shape=(94430, 1))

## Robust Scalar

In [58]:
scalar = RobustScaler()
robust_data = scalar.fit_transform(new_df)
robust_data

array([[ 8.56873833e+00],
       [-2.74707755e-02],
       [ 3.63683802e+01],
       ...,
       [-9.41714637e-03],
       [-2.08801016e-02],
       [-2.08801016e-02]], shape=(94430, 1))